### ISSUE TITLE
Freeze/Crash when attempting to load the mod on either game

### ISSUE THREAD

**Issue by CornObjects** [shiiion/metroid-prime-source-mod#2]
When attempting to load the mod for Prime 1, using Primehack 1.0.4 and Metroid Prime v1.00 as directed, Primehack crashes silently and completely with no notice of what went wrong. And with Prime 2, using Primehack 1.0.6 plus Metroid Prime 2 NTSC as directed, it simply freezes forever on a black screen before the Nintendo logo at 0 FPS.

Both games are in ISO format, and not NKIT or RVZ. I've tried both loading the mods prior to launching their respective games, and also loading the mods after launching each game, and they both have the same results regardless. As far as I can tell, I'm not missing anything in terms of files or what I'm doing to try and make it work. The only thing I haven't tried is attempting to build from source, which is something I'm not very familiar with aside from having issues with doing that for other projects in the past, so I'd much prefer to use an actual release like the one available instead.

Unless I'm missing something obvious, there must be something wrong with the actual mods.

**Comment by vyuuui** [comment]
Did you increase the emulated RAM? It needs to be set to 32 MB.
![image](https://github.com/shiiion/metroid-prime-source-mod/assets/92327340/32d84808-0034-4e15-9396-ba6853c0d820)

**Comment by CornObjects** [comment]
I actually wasn't aware of that, gave it a try and the Prime 1 version of the mod booted just fine, works perfectly in-game as well so I assume the same will be true for Prime 2. Thanks for telling me how to get it running, and sorry about opening an issue, like I said I had no idea if I was just missing something obvious or it had been broken by some kind of weird bug.
